# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sales-agent"
client_id = "137fe263d29e97e62c6d535ab9c23f95"
application_url = "https://daughters-spotlight-pregnant-land.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events, read_products"

[auth]
redirect_urls = [
  "https://daughters-spotlight-pregnant-land.trycloudflare.com/auth/callback",
  "https://daughters-spotlight-pregnant-land.trycloudflare.com/auth/shopify/callback",
  "https://daughters-spotlight-pregnant-land.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c57f5b6f.myshopify.com"
