# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sales-associate"
client_id = "601c1486133ec82b7b8965e2afcf84d6"
application_url = "https://sunset-maui-controllers-competing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events,read_products,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://sunset-maui-controllers-competing.trycloudflare.com/auth/callback",
  "https://sunset-maui-controllers-competing.trycloudflare.com/auth/shopify/callback",
  "https://sunset-maui-controllers-competing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-91d3669c.myshopify.com"
